<a href="https://colab.research.google.com/github/Heartz00/MyHamoyeStagestag_alongCode/blob/master/stageC_tag_along_codes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/content/Data_for_UCI_named.csv')
df

tau1      tau2      tau3      tau4        p1        p2        p3  \
0     2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1     9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2     8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3     0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4     3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
...        ...       ...       ...       ...       ...       ...       ...   
9995  2.930406  9.487627  2.376523  6.187797  3.343416 -0.658054 -1.449106   
9996  3.392299  1.274827  2.954947  6.894759  4.349512 -1.663661 -0.952437   
9997  2.364034  2.842030  8.776391  1.008906  4.299976 -1.380719 -0.943884   
9998  9.631511  3.994398  2.757071  7.821347  2.514755 -0.966330 -0.649915   
9999  6.530527  6.781790  4.349695  8.673138  3.492807 -1.390285 -1.532193   

            p4        g1        g2        g3        g4      stab     stabf  
0    -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1    -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2    -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3    -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4    -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  
...        ...       ...       ...       ...       ...       ...       ...  
9995 -1.236256  0.601709  0.779642  0.813512  0.608385  0.023892  unstable  
9996 -1.733414  0.502079  0.567242  0.285880  0.366120 -0.025803    stable  
9997 -1.975373  0.487838  0.986505  0.149286  0.145984 -0.031810    stable  
9998 -0.898510  0.365246  0.587558  0.889118  0.818391  0.037789  unstable  
9999 -0.570329  0.073056  0.505441  0.378761  0.942631  0.045263  unstable  

[10000 rows x 14 columns]

In [3]:
df.drop(columns='stab', inplace=True)

Check for the unique values in column -(stabf)

In [4]:
df.stabf.value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

create the features variable

In [5]:
#drop the target variable from the features
#stabf is the target
features=df.drop(columns=['stabf'])
features.head()

tau1      tau2      tau3      tau4        p1        p2        p3  \
0  2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1  9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2  8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3  0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4  3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   

         p4        g1        g2        g3        g4  
0 -1.723086  0.650456  0.859578  0.887445  0.958034  
1 -1.255012  0.413441  0.862414  0.562139  0.781760  
2 -0.920492  0.163041  0.766689  0.839444  0.109853  
3 -0.997374  0.446209  0.976744  0.929381  0.362718  
4 -0.554305  0.797110  0.455450  0.656947  0.820923

Convert the target variable to numerical values using label encoder.

In [6]:
from sklearn.preprocessing import LabelEncoder
target=LabelEncoder().fit_transform(df['stabf'])
target

array([1, 0, 1, ..., 0, 1, 1])

Standardize the features 

In [7]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
features = scaler.fit_transform(features)
features[0:5]

array([[-0.83537431, -0.79131661,  1.14170354,  1.65210289,  0.01739718,
         1.0794055 , -0.01707819, -1.09254499,  0.45746733,  1.22001311,
         1.32162751,  1.57902607],
       [ 1.47829663, -0.12670487, -0.80311147, -1.41504291,  1.75212436,
        -1.59361879, -1.43815844, -0.01157525, -0.40679143,  1.23035426,
         0.13542358,  0.93625569],
       [ 1.35709296,  1.31213982, -0.80349871, -1.47150374, -0.45849151,
         0.09825304, -0.06283962,  0.76096342, -1.3198525 ,  0.88129868,
         1.14659574, -1.51380226],
       [-1.65313833,  0.88228867, -0.27835446, -1.06090088,  0.28425038,
         0.51390386, -1.59104623,  0.58341424, -0.2873044 ,  1.64725009,
         1.47454259, -0.59175046],
       [-0.77154307,  0.86010818, -0.11166965,  1.68011424, -0.2980753 ,
         0.28744967, -1.3763432 ,  1.60663583,  0.99222554, -0.25361001,
         0.48113255,  1.07906277]])

Split the data into training and testing set.

In [8]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(features, target, test_size=0.2, random_state=1)

Train the data with a RandomForestClassifier

In [9]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(random_state=1)
rf_model =rf.fit(x_train, y_train)
rf_model

RandomForestClassifier(random_state=1)

Train the data with a Extra Trees Classifier

In [10]:
from sklearn.ensemble import ExtraTreesClassifier
ET = ExtraTreesClassifier(random_state=1)
ET_model = ET.fit(x_train,y_train)
ET_model

ExtraTreesClassifier(random_state=1)

Used Randomized Search CV to tune the Extra tree classifier to the best hyperparameters

In [11]:
from sklearn.model_selection import RandomizedSearchCV
model = ExtraTreesClassifier(random_state=1)
parameters = {
    'n_estimators' : [100, 200, 300, 500, 1000],
    'min_samples_leaf': [1,2,3,4,5,10,20],
    'max_features': [1,2,3,4,5,6,7,8]}
randm_src = RandomizedSearchCV(estimator=model, param_distributions = parameters,
                               cv = 5, n_iter = 10, n_jobs=-1, scoring='accuracy', random_state=1, verbose=1)
randm_src.fit(x_train, y_train)                 


Fitting 5 folds for each of 10 candidates, totalling 50 fits


RandomizedSearchCV(cv=5, estimator=ExtraTreesClassifier(random_state=1),
                   n_jobs=-1,
                   param_distributions={'max_features': [1, 2, 3, 4, 5, 6, 7,
                                                         8],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 10,
                                                             20],
                                        'n_estimators': [100, 200, 300, 500,
                                                         1000]},
                   random_state=1, scoring='accuracy', verbose=1)

Print the best hyperparameter

In [12]:
randm_src.best_estimator_

ExtraTreesClassifier(max_features=7, min_samples_leaf=3, n_estimators=1000,
                     random_state=1)

Train the data with a XGBoost model

In [13]:
import xgboost as xgb
xgb_model =xgb.XGBClassifier(random_state=1)
xgb_model = xgb_model.fit(x_train, y_train)
xgb_model

XGBClassifier(random_state=1)

Train the data with a light Gradient boosting model

In [14]:
import lightgbm as lgb
from lightgbm import LGBMClassifier
lg = LGBMClassifier(random_state=1)
lg_model = lg.fit(x_train, y_train)
lg_model

LGBMClassifier(random_state=1)

Import the metrics for classification model

In [15]:
from sklearn.metrics import accuracy_score, confusion_matrix, recall_score, f1_score, jaccard_score, precision_score

Check for the recall of each model

In [16]:
#create a for loop that prints out the model and its respective metrics
models = [rf_model, ET_model, randm_src,xgb_model,lg_model]
names = ['rf_model', 'ET_model', 'randm_src','xgb_model','lg_model']
result=[]
for model in models:
  recall = recall_score(y_true = y_test, y_pred = model.predict(x_test), pos_label=0)
  result.append(recall)
recall_dictionary = (dict(zip(names, result)))
recall_dictionary

{'rf_model': 0.8778089887640449,
 'ET_model': 0.851123595505618,
 'randm_src': 0.8806179775280899,
 'xgb_model': 0.8469101123595506,
 'lg_model': 0.9115168539325843}

Check for the precision score of each model

In [17]:
result1=[]
for model in models:
  precision = precision_score(y_true = y_test, y_pred = model.predict(x_test), pos_label=0)
  result1.append(precision)
precision_dictionary = (dict(zip(names, result1)))
precision_dictionary

{'rf_model': 0.9191176470588235,
 'ET_model': 0.9409937888198758,
 'randm_src': 0.9372197309417041,
 'xgb_model': 0.9206106870229007,
 'lg_model': 0.9392185238784371}

Check for the f1_score of each model

In [18]:
result2=[]
for model in models:
  f1 = f1_score(y_true = y_test, y_pred = model.predict(x_test), pos_label=0)
  result2.append(f1)
f1_dictionary = (dict(zip(names, result2)))
f1_dictionary

{'rf_model': 0.8979885057471264,
 'ET_model': 0.8938053097345133,
 'randm_src': 0.9080376538740045,
 'xgb_model': 0.8822238478419898,
 'lg_model': 0.925160370634355}

Check for the accuracy of each model

In [19]:
result3=[]
for model in models:
  accuracy = accuracy_score(y_true = y_test, y_pred = model.predict(x_test))
  result3.append(accuracy)
accuracy_dictionary = (dict(zip(names, result3)))
accuracy_dictionary

{'rf_model': 0.929,
 'ET_model': 0.928,
 'randm_src': 0.9365,
 'xgb_model': 0.9195,
 'lg_model': 0.9475}

Find the feature importance using the optimal ExtraTReeClassifier

In [32]:
#the optimal ExtraTreeClassifier is saved as randm_src
important = randm_src.best_estimator_.feature_importances_
important

array([0.13189067, 0.13441286, 0.1289826 , 0.12988414, 0.01312323,
       0.01617939, 0.01622728, 0.01588377, 0.09805609, 0.10365519,
       0.10673918, 0.1049656 ])

In [25]:
#print the features to compare with the features importance, note that stabf is not part of the features
df.columns

Index(['tau1', 'tau2', 'tau3', 'tau4', 'p1', 'p2', 'p3', 'p4', 'g1', 'g2',
       'g3', 'g4', 'stabf'],
      dtype='object')

We have tau2 and p1 as the most and least important feature respectively